[pytest]
DJANGO_SETTINGS_MODULE = txcore.test_settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts =
    --cov=txcore
    --cov-report=term-missing
    -v
    -p no:warnings
