# Generated by Django 4.2.13 on 2026-06-26 20:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('matched', models.IntegerField(default=0)),
                ('discrepancies', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationDiscrepancy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=100)),
                ('discrepancy_type', models.CharField(choices=[('amount_mismatch', 'Amount Mismatch'), ('not_found', 'Transaction Not Found'), ('status_mismatch', 'Status Mismatch'), ('duplicate', 'Duplicate Entry')], max_length=30)),
                ('expected_amount', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('actual_amount', models.DecimalField(decimal_places=4, max_digits=19, null=True)),
                ('expected_status', models.CharField(blank=True, max_length=20)),
                ('actual_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_set', to='reconciliation.reconciliationrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['run', 'discrepancy_type'], name='reconciliat_run_id_464291_idx'), models.Index(fields=['reference', 'resolved'], name='reconciliat_referen_e157d8_idx')],
            },
        ),
    ]
