# Generated by Django 4.2.13 on 2026-10-09 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationdiscrepancy',
            name='actual_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='reconciliationdiscrepancy',
            name='expected_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AlterField(
            model_name='reconciliationdiscrepancy',
            name='discrepancy_type',
            field=models.CharField(choices=[('amount_mismatch', 'Amount Mismatch'), ('not_found', 'Transaction Not Found'), ('status_mismatch', 'Status Mismatch'), ('currency_mismatch', 'Currency Mismatch'), ('duplicate', 'Duplicate Entry')], max_length=30),
        ),
    ]
